# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef8eb956a9cbe8eabb954bebdc29f33239aa61f18f719db96dd53b511a5b2e186070651d0446043d1e436826b685e69ad37d16766e55932958f397761e244606

test:
  secret_key_base: cb34ac16fdbb4e8fb8f5120744fe2137eded9b515e19d544b7927d709630ee66483acf4616dd2d3420d45d439a719f81be5a4f3772aef416ee7109e550a8dfd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
